baseURL = "https://terracommuni.org/"
# baseURL = "https://siggg.github.io/TerraCommuni/"
defaultContentLanguage = "en"
title = "TerraCommuni"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
copyright = '© 2023 Jean Millerat, Agence Française de Développement'
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

# canonifyURLs = true
publishDir = "public"

[Params]
  # subtitle = "Build a beautiful and simple website in minutes"
  mainSections = ["post","posts"]
  logo = "img/logo.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  selfhosted = true
  etherscan_API_key = "E6FW5YGBWRTQ51D6KJMIZCQNJ2AP5X7866"
  web3_storage_JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGI5OTViOTI1MjI2NmY5ZjZkOUJmQzk2MjEwMkQ1ODg1MjdkOTMyOUIiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2ODg0ODc2NzQwMTIsIm5hbWUiOiIyMDIzLTA3LTA0X3B1dC1maWxlcyJ9.QLpvshXTB7HHF6CeZPivkUToPd7H1pMRrVNIYCXW1Q0"				
  IPFS_gateway = "https://ipfs.io/ipfs/"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Jean Millerat, Agence Française de Développement"
  website = "https://www.afd.fr/"
  email = "jean.terracommuni@wecena.com"
  # facebook = "jean.millerat"
  github = "siggg"
  gitlab = "siggg"
  # bitbucket = "username"
  # twitter = "siggg"
  # reddit = "username"
  linkedin = "https://www.linkedin.com/in/jean-millerat-8b1414/"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # youtube = "user/sig007007" # or channel/channelname
  # instagram = "username"
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
  # 500px = "username"
  # codepen = "username"
  # mastodon = "url"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"
  # medium = "username"
  # discord = "invite code (https://discord.gg/XXXXXXX)"
  # strava = "userid"

[[menu.main]]
    name = "Ceremonies"
    url = "page/ceremonies"
    weight = 1

[[menu.main]]
    name = "Contribute"
    url = "post/howto"
    weight = 10

[[menu.main]]
    name = "Protocol"
    url = "post/guide"
    weight = 20
	
[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 40

[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
	weight = 1
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
	weight = 2
