baseurl = "https://siggg.github.io/"
languageCode = "en-us"
title = "Welcome to TerraCommuni"
theme = "hugo-split-gallery"
paginate = 2
Copyright = "© Jean Millerat, Agence Française de Développement"
canonifyurls = true

[params]
description = "Enter your personal description"
authorlocation = "Paris, France"
cover = "images/cover.png"
author = "Jean Millerat"
logo = "images/logo.png"
githubName = "siggg"
linkedinName = "Jean Millerat"
email = "your email"
instagramName = "your ins name"
hideHUGOSupport = false

[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "Contact"
weight = 0
identifier = "contact" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/contact"

[[menu.main]]
name = "Blog"
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/post"
weight = 40

[permalinks]
# post = "/:slug/"​

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
